#!/bin/bash
echo "######################### $USER@$HOSTNAME"                                                                                                             
echo "#⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿# ---------------"                                                                                                              
echo "#⣿⣿█▀▀█⣿⣿█▀▀█⣿█▀▀█⣿▀▀▀█⣿# CPU: $(grep "model name" /proc/cpuinfo | head -1 | cut -d ':' -f2 | sed 's/with Radeon Graphics//' | xargs)"                       
echo "#⣿⣿█▄▀█⣿⣿█▄▄█⣿⣿⣿▀▄⣿⣿⣿█⣿⣿# $(free -m | awk 'NR==2{printf "RAM: %.1fGB/%.1fGB", $3/1024, $2/1024}')"                                                     
echo "#⣿⣿█▄▄█⣿⣿█⣿⣿⣿⣿█▄▄█⣿⣿▐▌⣿⣿# ↑: $(awk -F. '{d=int($1/86400); h=int(($1%86400)/3600); m=int(($1%3600)/60); printf "%dD:%dH:%dM", d, h, m}' /proc/uptime)"
echo "#⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿# $(basename "$SHELL" | tr '[:lower:]' '[:upper:]')"                                                                             
echo "#⣿⣿█▀█⣿⣿▀▀█▀▀⣿█▀▀█⣿▀▀▀█⣿# KONSOLE: $(basename "$TERM" | tr '[:lower:]' '[:upper:]' | sed 's/-256COLOR//')"                                               
echo "#⣿█▄▄█▄⣿⣿⣿█⣿⣿⣿█▄▀█⣿⣿⣿█⣿⣿# WM: i3 4.24 (X11)"                                                                                                                
echo "#⣿⣿⣿⣿█⣿⣿⣿⣿█⣿⣿⣿█▄▄█⣿⣿▐▌⣿⣿# OS: $(awk -F= '/^NAME=/ {print toupper($2)}' /etc/os-release | tr -d '"')"                                                        
echo "#⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿#"    
echo "#########################"
echo "                         "
echo -e "$(~/Scripts/showkcolor.sh)"
